#lang sicp

(define (make-account balance account-password)
  (define incorrect-password-count 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (check-password password)
    (if (eq? password account-password)
        (begin (set! incorrect-password-count 0)
               true)
        (begin (set! incorrect-password-count (+ incorrect-password-count 1))
               (if (> incorrect-password-count 7)
                   (call-the-cops))
               false)))
  (define (dispatch password m)
    (cond ((not (check-password password)) 
           (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define (call-the-cops)
  (display "Calling the cops...")
  (newline))
